version: '3.9'

services:
  tq-backend:
    image: pprajapa/tq-backend:latest
    container_name: tq-backend
    networks:
      - tq-network
    ports:
      - "5000"  # Specify the port for internal communication

  tq-frontend-desktop:
    image: pprajapa/tq-frontend-desktop:latest
    container_name: tq-frontend-desktop
    ports:
      - "4000:4000"  # Map the container's port 4000 to the host's port 4000
    networks:
      - tq-network
    depends_on:
      - tq-backend
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    devices:
      - /dev/dri:/dev/dri

  tq-frontend-web:
    image: pprajapa/tq-frontend-web-light:latest
    container_name: tq-frontend-web
    ports:
      - "3000:3000"  # Map the container's port 3000 to the host's port 3000
    networks:
      - tq-network
    depends_on:
      - tq-backend
    labels:
      kompose.service.type: LoadBalancer
    # Comment: "Frontend service should be running. Visit http://localhost:3000/apptq_frontend.html"
  
  reverse-proxy:
    image: pprajapa/tq-reverse-proxy:latest
    container_name: tq-reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - tq-backend
      - tq-frontend-web
    networks:
      - tq-network
      
networks:
  tq-network:
    driver: bridge
