version: '3.9'

services:
  tq-backend-local:
    image: pprajapa/tq-backend:latest
    container_name: tq-backend-local
    networks:
      - tq-network
    ports:
      - "5000:5000"  # Specify the port for internal communication

  tq-frontend-desktop:
    image: pprajapa/tq-frontend-desktop:latest
    container_name: tq-frontend-desktop
    ports:
      - "4000:4000"  # Map the container's port 4000 to the host's port 4000
    networks:
      - tq-network
    depends_on:
      - tq-backend-local
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # Linux only
    environment:
      - DISPLAY=${DISPLAY} # use for Linux only, comment out for MacOS & Windows
      # - DISPLAY=host.docker.internal:0 # use for MacOS & Windows only, comment out for Linux
    devices:
      - /dev/dri:/dev/dri # use for Linux only, comment out for MacOS & Windows
    ########################################
    # Instructions for MacOS:
    # 1. Install XQuartz
    # 2. Open XQuartz and go to Preferences > Security and check the box for "Allow connections from network clients"
    # 3. Restart XQuartz
    # 4. Run the following command in the terminal:
    #    xhost +
    # 5. Uncomment the following line:
    #    - DISPLAY=host.docker.internal:0
    # 6. Comment out the following line:
    #    - DISPLAY=${DISPLAY}
    ########################################
    ########################################
    # Instructions for Windows:
    # 1. Install VcXsrv
    # 2. Open VcXsrv and go with the default settings
    # 3. Run the following command in the terminal:
    #    set DISPLAY=host.docker.internal:0
    # 4. Uncomment the following line:
    #    - DISPLAY=host.docker.internal:0
    # 5. Comment out the following line:
    #    - DISPLAY=${DISPLAY}
    ########################################
    
networks:
  tq-network:
    name: tq-network
    driver: bridge
