version: '3.9'

services:
  tq-backend:
    image: pprajapa/tq-backend:latest
    container_name: tq-backend
    networks:
      - tq-network
    ports:
      - "5000"  # Specify the port for internal communication

  tq-frontend-web:
    image: pprajapa/tq-frontend-web-light:latest
    container_name: tq-frontend-web
    ports:
      - "3000:3000"  # Map the container's port 3000 to the host's port 3000
    networks:
      - tq-network
    depends_on:
      - tq-backend
    labels:
      kompose.service.type: LoadBalancer
    # Comment: "Frontend service should be running. Visit http://localhost:3000/apptq_frontend.html"
  
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - tq-backend
      - tq-frontend-web
    networks:
      - tq-network
        
networks:
  tq-network:
    driver: bridge
